apiVersion: v1
version: 0.4.3
appVersion: ">=2204.0.0"
kubeVersion: ">=1.16.0"
name: soneta
description: Soneta products Helm chart for Kubernetes
keywords: 
    - enova
    - enova365
    - triva
    - soneta
home: https://enova.pl
sources:
    - https://github.com/soneta/helm-charts/tree/main/charts/soneta
    - https://github.com/soneta/helm-charts
maintainers:
    - name: bartcho
    - name: chodakq
#       email:
#       url:
# icon:
annotations:
    artifacthub.io/containsSecurityUpdates: "false"
    artifacthub.io/changes: |
        - web, webapi, webwcf pod ports changed from 80 to 8080 - net8 images requirement