apiVersion: v2
version: 0.5.0-alpha.3
appVersion: ">=2504.0.0"
kubeVersion: ">=1.19.0"
name: soneta
description: Soneta products Helm chart for Kubernetes
keywords: 
    - enova
    - enova365
    - triva
    - soneta
home: https://enova.pl
sources:
    - https://github.com/soneta/helm-charts/tree/main/charts/soneta
    - https://github.com/soneta/helm-charts
maintainers:
    - name: bartcho
    - name: chodakq
#       email:
#       url:
# icon:
annotations:
    artifacthub.io/containsSecurityUpdates: "false"
    artifacthub.io/changes: |
        - "Extended and updated the parameterization examples section in README.md"
        - "Added detailed configuration examples: image, orchestrator, resources, env, PVC, volumes, ingress"
        - "Added comments and descriptions to selected YAML fragments"
        - "Organized and unified the Helm values.yaml configuration examples section"