# Default values for soneta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

adminMode: false
replicaCount: 1
image:
  product: "standard"
  tag: "2504.2.4"
  repository: ""
  scheduler: false
  webapi: false
  webwcf: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  server:
    type: ClusterIP

appsettings: 
  CommHub:
    GarnetServer:
      MemorySize: "16m"
      IndexSize: "16m"
      PageSize: "4m"

ingress:
  enabled: false
  # releaseAutoAnnotation: 
  #   key: nginx.ingress.kubernetes.io/session-cookie-name
  #   prefix: ""
  #   postfix: "-INGRESSCOOKIE"
  # annotations:
  #   nginx.ingress.kubernetes.io/affinity: cookie 
  class: nginx
  host: enova365.pl
  # tlsSecretName: soneta-ingress-tls

resources:
  pvc:
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Mi
      # storageClassName: azurefile
  web:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  webapi:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  webwcf:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  orchestrator:
    limits:
      cpu: 200m
      memory: 384Mi
    requests:
      cpu: 50m
      memory: 128Mi
  router:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  commhub:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  server:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi
  scheduler:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi
  admin:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi

nodeSelector: []

tolerations: []

affinity: {}

volumes:
  all: []
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []

envs:
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []

args:
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []