# Default values for soneta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  product: "standard"
  tag: "2204.0.0"
  repository: ""
  scheduler: false
  webapi: false
  webwcf: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  server:
    type: ClusterIP
    port0Name: tcp0
    port0: 22000
    port3Name: tcp3
    port3: 22003

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  host: enova365.pl
  tlsSecretName: soneta-ingress-tls

resources:
  pvc: {}
  smb: {}
  afs: {}
  web:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 384Mi
  webapi:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  server:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi
  scheduler:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi

nodeSelector: []

tolerations: []

affinity: {}

volumes:
  all: []
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []

envs:
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []

args:
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []