# Default values for soneta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  product: "standard"
  tag: "2110.1.3"
  repository: ""
  scheduler: false
  webapi: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  server:
    type: ClusterIP
    port0Name: tcp0
    port0: 22000
    port3Name: tcp3
    port3: 22003

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  host: enova365.pl
  tlsSecretName: soneta-ingress-tls

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  pvc:
    enabled: false
    requests: 5Gi
    mountPath: "D:"
  afs:
    enabled: false
    # accountName: your azure storage account name 
    # accountKey: your azure storage account key
    # shareName: your azure storage share name
    mountPath: "Z:"
  web:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 384Mi
  webapi:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  server:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi
  scheduler:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 384Mi

nodeSelector:
  kubernetes.io/os : windows

tolerations: []

affinity: {}

envs:
  web: []
  webapi: []
  server: []