# yaml-language-server: $schema=./values.schema.json
# Default values for soneta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

adminMode: false
replicaCount: 1
image:
  product: "standard"
  tag: "2504.2.4"
  webTagPostfix: -alpine
  serverTagPostfix: -alpine
  repository: ""
  scheduler: false
  webapi: false
  webwcf: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  server:
    type: ClusterIP

appsettings: 
  CommHub:
    GarnetServer:
      MemorySize: "16m"
      IndexSize: "16m"
      PageSize: "4m"
  HealthCheck:
    Enabled: true

ingress:
  enabled: false
  # releaseAutoAnnotation: 
  #   key: nginx.ingress.kubernetes.io/session-cookie-name
  #   prefix: ""
  #   postfix: "-INGRESSCOOKIE"
  # annotations:
  #   nginx.ingress.kubernetes.io/affinity: cookie 
  class: nginx
  host: enova365.pl
  # tlsSecretName: soneta-ingress-tls

default-small-component-resources: &default-small-component-resources
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

default-big-component-resources: &default-big-component-resources
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 384Mi

resources:
  pvc:
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Mi
  web:
    <<: *default-small-component-resources
  webapi:
    <<: *default-small-component-resources
  webwcf:
    <<: *default-small-component-resources
  orchestrator:
    <<: *default-small-component-resources
  router:
    <<: *default-small-component-resources
  commhub:
    <<: *default-small-component-resources
  server:
    <<: *default-big-component-resources
  scheduler:
    <<: *default-big-component-resources
  admin:
    <<: *default-big-component-resources

nodeSelector: []

tolerations: []

affinity: {}

volumes:
  all: []
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []
  admin: []

envs:
  all: []
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []
  admin: []

args:
  all: []
  frontend: []
  web: []
  webapi: []
  webwcf: []
  backend: []
  server: []
  scheduler: []
  admin: []