{{- if .Values.image.orchestrator }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname.orchestrator" . }}
  labels:
{{ include "soneta.labels.orchestrator" . | indent 4 }}
data:
  Web.yaml: |-
    {{ include "soneta.deployment.web" . | nindent 4 | trim }}
  Server.yaml: |-
    {{ include "soneta.deployment.server" . | nindent 4 | trim }}
{{- end -}}