{{- if and .Values.appsettings }}
{{- $component := (list . "appsettings") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname" $component }}
  labels:
{{ include "soneta.labels" $component | indent 4 }}
data:
  appsettings.yaml: |-
{{ merge ((include "soneta.templates" . ) | fromYaml) .Values.appsettings | toYaml | indent 4 }}
{{- end -}}