{{- if .Values.image.orchestrator }}
{{- $component := (list . "orchestrator") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname" $component }}
  labels:
{{ include "soneta.labels" $component | indent 4 }}
data:
  appsettings.yaml: |-
    orchestrator:
      kubernetes:
        composition:
          frontend:
            routerendpoint: http://{{ include "soneta.fullname" (list . "router") }}-1:80
          router:
            enabled: true
            overrides:
              orchestratorendpoint: http://{{ include "soneta.fullname" $component }}:80
          web:
            enabled: true
          server:
            enabled: true
        templates:
{{- $router := (list . "router") }}          
          router:
            service: |-
              {{ include "soneta.service" $router | indent 14 | trim }}
            pod: |-
              {{ include "soneta.pod" $router | indent 14 | trim }}
{{- $web := (list . "web") }}          
          web:
            service: |-
              {{ include "soneta.service" $web | indent 14 | trim }}
            pod: |-
              {{ include "soneta.pod" $web | indent 14 | trim }}
{{- $server := (list . "server") }}          
          server:
            service: |-
              {{ include "soneta.service" $server | indent 14 | trim }}
            pod: |-
              {{ include "soneta.pod" $server | indent 14 | trim }}
{{- end -}}