{{- $component := (list . "server") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname" $component }}
  labels:
{{ include "soneta.labels" $component | indent 4 }}
data:
  lista-baz-danych: |-
    {{ .Values.listaBazDanych | required "A valid .Values.listaBazDanych entry is required!"  | nindent 4 | trim }}