apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname.server" . }}
  labels:
{{ include "soneta.labels.server" . | indent 4 }}
data:
  lista-baz-danych: |-
    {{ .Values.listaBazDanych | required "A valid .Values.listaBazDanych entry is required!"  | nindent 4 | trim }}
