{{- if .Values.image.orchestrator }}
{{- $component := (list . "orchestrator") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soneta.fullname" $component }}
  labels:
{{ include "soneta.labels" $component | indent 4 }}
data:
  appsettings.yaml: |-
    orchestrator:
      kubernetes:
        templates:
          web:
{{- $web := (list . "web") }}          
            {{ include "soneta.pod" $web | nindent 12 | trim }}
  web.yaml: |-
    {{ include "soneta.deployment.web" . | nindent 4 | trim }}
  server.yaml: |-
    {{ include "soneta.deployment.server" . | nindent 4 | trim }}
{{- end -}}