{{- if .Values.image.webwcf -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soneta.fullname.webwcf" . }}
  labels:
{{ include "soneta.labels.webwcf" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "soneta.labels.webwcf" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soneta.labels.webwcf" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-webwcf"
          image: "{{ .Values.image.repository }}soneta/web.{{ .Values.image.product}}:{{ .Values.image.tag }}{{ include "soneta.web.tagPostfix" . }}"
          imagePullPolicy: IfNotPresent
{{ include "soneta.webwcf.command_args" . | indent 10 }}
          env:
            {{- if .Values.envs.webwcf }}
            {{- toYaml .Values.envs.webwcf | nindent 12 }}
            {{- end }}
            - name: Soneta_WebWcf__ServerEndpoint
              value: {{ include "soneta.web.enpointProtocol" . }}$({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_HOST):$({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_PORT)
            - name: SONETA_SERVER_ENDPOINTS
              value: {{ include "soneta.web.enpointProtocol" . }}$({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_HOST):$({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_PORT)
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.webwcf | nindent 12 }}
      nodeSelector:
        kubernetes.io/os: {{ include "soneta.web.nodeselector.os" . }}
      {{- with .Values.nodeSelector }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}