{{- if .Values.image.webwcf -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soneta.fullname.webwcf" . }}
  labels:
{{ include "soneta.labels.webwcf" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "soneta.labels.webwcf" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soneta.labels.webwcf" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-webwcf"
          image: "{{ .Values.image.repository }}soneta/web.{{ .Values.image.product}}:{{ .Values.image.tag }}{{ include "soneta.web.tagPostfix" . }}"
          imagePullPolicy: IfNotPresent
          {{- include "soneta.webwcf.commands" . | nindent 10 }}
          args:
            {{- include "soneta.args" .Values.args.frontend | indent 12 }}
            {{- include "soneta.args" .Values.args.webwcf | indent 12 }}
          env:
            {{- include "soneta.envs.frontend" . | nindent 12}}
            {{- include "soneta.envs" .Values.envs.frontend | indent 12 }}
            {{- include "soneta.envs" .Values.envs.webwcf | indent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.webwcf | nindent 12 }}
          volumeMounts:
            {{- include "soneta.volumeMounts" .Values.volumes.all | indent 12 }}
            {{- include "soneta.volumeMounts" .Values.volumes.frontend | indent 12 }}
            {{- include "soneta.volumeMounts" .Values.volumes.webwcf | indent 12 }}
      volumes:
        {{- include "soneta.volumeMounts" .Values.volumes.all | indent 8 }}
        {{- include "soneta.volumes" .Values.volumes.frontend | indent 8 }}
        {{- include "soneta.volumes" .Values.volumes.webwcf | indent 8 }}
      nodeSelector:
        kubernetes.io/os: {{ include "soneta.web.nodeselector.os" . }}
      {{- with .Values.nodeSelector }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}