{{- if not .Values.appsettings.orchestrator.kubernetes -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soneta.fullname.scheduler" . }}
  labels:
{{ include "soneta.labels.scheduler" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "soneta.selectors.scheduler" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soneta.labels.scheduler" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-server-{{ .Values.image.product}}"
          image: "{{ .Values.image.repository }}soneta/server.{{ .Values.image.product}}:{{ .Values.image.tag }}{{ include "soneta.server.tagPostfix" . }}"
          imagePullPolicy: IfNotPresent
          command: {{ include "soneta.scheduler.command" . }}
          args: 
            {{- include "soneta.scheduler.args" . | nindent 12 }}
          env:
            - name: SCHEDULER
              value: 'True'
            {{- include "soneta.envs.dbconfig" . | nindent 12 }}
            {{- include "soneta.envs" .Values.envs.all | indent 12 }}
            {{- include "soneta.envs" .Values.envs.backend | indent 12 }}
            {{- include "soneta.envs" .Values.envs.scheduler | indent 12 }}
          resources:
            {{- toYaml .Values.resources.scheduler | nindent 12 }}
          volumeMounts:
            {{- include "soneta.volumeMounts.listaBazDanych" . | nindent 12 }}
            {{- include "soneta.volumeMounts" .Values.volumes.all | indent 12 }}
            {{- include "soneta.volumeMounts" .Values.volumes.backend | indent 12 }}
            {{- include "soneta.volumeMounts" .Values.volumes.scheduler | indent 12 }}
      volumes:
        {{- include "soneta.volumes.listaBazDanych" . | nindent 8 }}
        {{- include "soneta.volumes" .Values.volumes.all | indent 8 }}
        {{- include "soneta.volumes" .Values.volumes.backend | indent 8 }}
        {{- include "soneta.volumes" .Values.volumes.server | indent 8 }}
      nodeSelector:
        kubernetes.io/os: {{ include "soneta.server.nodeselector.os" . }}
      {{- with .Values.nodeSelector }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
