{{- if .Values.image.webapi -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soneta.fullname.webapi" . }}
  labels:
{{ include "soneta.labels.webapi" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "soneta.labels.webapi" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soneta.labels.webapi" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-webapi"
          image: "{{ .Values.image.repository }}soneta/web.api:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- if .Values.envs.webapi }}
            {{- toYaml .Values.envs.webapi | nindent 12 }}
            {{- end }}
            - name: SONETA_SERVER_ENDPOINTS
              value: $({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_HOST):$({{ print ( include "soneta.fullname.server" . ) | upper | replace "-" "_" }}_SERVICE_PORT)
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.webapi | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}