{{- if and (not (include "soneta.isAdminMode" .)) (.Values.image.webapi) (not (include "soneta.isOrchestrator" .)) -}}
{{- $component := (list . "webapi") -}}
{{ include "soneta.deployment" $component }}
{{- end }}