apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "soneta.fullname" (list . "pvc") }}
spec:
  {{- toYaml .Values.resources.pvc.spec | nindent 2 }}

{{- if .Values.pvcs }}
  {{- $top := . -}}
  {{- range $index, $pvc := .Values.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.name }}
spec:
  {{- toYaml $pvc.spec | nindent 2 }}
  {{- end }}
{{- end }}