{{- if .Values.secrets }}
  {{- $top := . -}}
  {{- range $index, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
type: Opaque
data:
    {{- range $dataIndex, $data :=  $secret.data }}
    {{ $data.key }}: {{ b64enc $data.value }}
    {{- end }}
  {{- end }}
{{- end }}