{{- if or (not .Values.listaBazDanych) .Values.resources.afs.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soneta.fullname.server" . }}
type: Opaque
data:
  {{- if not .Values.listaBazDanych }}
  server: {{ required "Database server address is required" .Values.database.server | b64enc }}
  db-name: {{ required "Database name is required" .Values.database.name | b64enc }}
  user: {{ required "Database user is required" .Values.database.user | b64enc }}
  password: {{ required "Database password is required" .Values.database.password | b64enc }}
  {{- end }}
  {{- if .Values.resources.afs.enabled }}
  azurestorageaccountname: {{ required "Azure storage account name is required" .Values.resources.afs.accountName | b64enc }}
  azurestorageaccountkey: {{ required "Azure storage account key is required" .Values.resources.afs.accountKey | b64enc }}
  {{- end }}
{{- end -}}