apiVersion: v1
kind: Service
metadata:
  name: {{ include "soneta.fullname.web" . }}
  labels:
{{ include "soneta.labels.web" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "soneta.labels.web" . | indent 4 }}
