{{- if .Values.image.orchestrator -}}
{{- $name := include "soneta.fullname" (list . "orchestrator") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
#   namespace: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - nodes
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - logs
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - create
  - delete
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ .Release.Name }}
{{- end -}}