{{- if .Values.image.webwcf -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "soneta.fullname.webwcf" . }}
  labels:
{{ include "soneta.labels.webwcf" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "soneta.labels.webwcf" . | indent 4 }}
{{- end }}